//---------------------------------------------------------------------------------------------------------------------------------//
//Mauricio Lima de Souza 06/10/2015                                                                                                //
//---------------------------------------------------------------------------------------------------------------------------------//
//Específico Rosenberger Domex                                                                                                     //
//retorno  .T. ou .F.
//        Se retornar falso, o MRP não irá considerar o produto como alternativo.
//        Se retornar verdadeiro, o MRP irá considerar o produto como alternativo.                                                                                                    //
//--------------------------------------------------------------------------------------------------------------------------------//
User Function A710VLALT()   
Local lRET:=.T.
Return(lRET)