//-------------------------------------------------------------------------------------------------------------------------------------------------//
//Mauricio Lima de Souza - 20/04/18 - OpusVp                                                                                                       //
//-------------------------------------------------------------------------------------------------------------------------------------------------//
//Especifico                                                                                                                                       //
//-------------------------------------------------------------------------------------------------------------------------------------------------//
//titulo provisorio imposto 6 meses                                                                                                                //
//-------------------------------------------------------------------------------------------------------------------------------------------------//

#INCLUDE "RWMAKE.CH"
#INCLUDE "TOPCONN.CH"
#include "tbiconn.ch"

User Function DOMPRVIP()
Local nX :=0

aemp := {"01","01"}
PREPARE ENVIRONMENT EMPRESA "01" FILIAL "01" USER 'MRP' PASSWORD 'Megasenha' Tables "SE2","SED"  Modulo "FIN"

dVENCTO  := DATE()
cNUM     := SPACE(09)
//EXEMPLO
dDATAATU := DATE()                           //15/06/2018
dDATC1   := (FirstDay(dDATAATU))-1           //31/05/2018
dDATC2   := (FirstDay(dDATC1))-1             //30/04/2018
dDATC3   := (FirstDay(dDATC2))-1             //31/03/2018
dDATC4   := (FirstDay(dDATC3))-1             //28/02/2018
dDATC5   := (FirstDay(dDATC4))-1             //31/01/2018
dDATC6   := FirstDay((FirstDay(dDATC5))-1 )  //01/12/2017

dDATP1   := (LASTDAY(dDATAATU))              //30/06/2018
dDATP2   := LASTDAY(LASTDAY(dDATP1)+1)       //31/07/2018
dDATP3   := LASTDAY(LASTDAY(dDATP2)+1)       //31/08/2018
dDATP4   := LASTDAY(LASTDAY(dDATP3)+1)       //30/09/2018
dDATP5   := LASTDAY(LASTDAY(dDATP4)+1)       //31/10/2018
dDATP6   := LASTDAY(LASTDAY(dDATP5)+1)       //30/11/2018


cQR1 :=" DELETE SE2010 WHERE E2_PREFIXO='DOM' AND E2_TIPO='PR' AND SUBSTRING(E2_NUM,1,3)='PRV' "
TCSQLEXEC(cQR1)

// criação tabela temporaria

cQUERY := " SELECT  "
cQUERY += " E2_FORNECE, "
cQUERY += " E2_LOJA, "
cQUERY += " E2_NATUREZ, "
cQUERY += " ED_DESCRIC,(SUM(E2_VALOR))/6 AS E2_VALOR"
cQUERY += " FROM SE2010  SE2,SED010 SED "
cQUERY += " WHERE E2_EMISSAO >='"+DTOS(dDATC6)+"' AND  E2_EMISSAO <='"+DTOS(dDATC1)+"' "
cQUERY += " AND E2_FORNECE IN ('ESTADO','INPS  ','MUNIC ','UNIAO ')  "
cQUERY += " AND SE2.D_E_L_E_T_=''  "
cQUERY += " AND SED.D_E_L_E_T_=''  "
cQUERY += " AND E2_NATUREZ=ED_CODIGO "
cQUERY += " GROUP BY E2_FORNECE,E2_LOJA,E2_NATUREZ,ED_DESCRIC  "
cQUERY += " ORDER BY E2_FORNECE,E2_LOJA,E2_NATUREZ,ED_DESCRIC  "

TcQuery cQuery Alias "TRB" New

SE2->(DBSELECTAREA('SE2'))
SE2->(DBSETORDER(2))

For nX :=1 to 6
	TRB->(DbGoTop())
	cPARCEL :='0'
	DO CASE
		CASE nX==1
			cNUM    :='PRV'+SUBSTR(DTOS(dDATP1),1,6)
			dVENCTO := dDATP1
		CASE nX==2
			cNUM    :='PRV'+SUBSTR(DTOS(dDATP2),1,6)
			dVENCTO := dDATP2
		CASE nX==3
			cNUM    :='PRV'+SUBSTR(DTOS(dDATP3),1,6)
			dVENCTO := dDATP3
		CASE nX==4
			cNUM    :='PRV'+SUBSTR(DTOS(dDATP4),1,6)
			dVENCTO := dDATP4
		CASE nX==5
			cNUM    :='PRV'+SUBSTR(DTOS(dDATP5),1,6)
			dVENCTO := dDATP5
		CASE nX==6
			cNUM    :='PRV'+SUBSTR(DTOS(dDATP6),1,6)
			dVENCTO := dDATP6
	ENDCASE
	DO WHILE .NOT. TRB->(EOF())
		nVALOR  :=0
		cQR2:= " SELECT SUM(E2_VALOR) AS E2_VALOR  "
		cQR2+= " FROM SE2010 "
		cQR2+= " WHERE E2_VENCREA >='"+DTOS(Firstday(dVENCTO))+"' AND E2_VENCREA<='"+DTOS(LastDay(dVENCTO))+"' "
		cQR2+= " AND D_E_L_E_T_='' "
		cQR2+= " AND E2_PREFIXO<>'DOM' "
		cQR2+= " AND E2_NATUREZ='"+TRB->E2_NATUREZ+"'  "
		cQR2+= " AND E2_VALOR>0 "
		TcQuery cQR2 Alias "TR2" New
		
		
		TR2->(DbGoTop())
		
		IF TR2->E2_VALOR>0
			nVALOR :=TRB->E2_VALOR-TR2->E2_VALOR
		ELSE
			nVALOR :=TRB->E2_VALOR
		ENDIF
		
		IF  nVALOR>0
			cPARCEL :=SOMA1(cPARCEL)
			//(2) E2_FILIAL+E2_NATUREZ+E2_NOMFOR+E2_PREFIXO+E2_NUM+E2_PARCELA+E2_TIPO+E2_FORNECE
			SE2->(DBSEEK(xFILIAL('SE2')+TRB->E2_NATUREZ+TRB->E2_FORNECE+'DOM'+cNUM))
			IF SE2->(FOUND())
				RecLock("SE2",.F.)
			ELSE
				RecLock("SE2",.T.)
			ENDIF
			E2_FILIAL  := xFILIAL('SE2')
			E2_PREFIXO :='DOM'
			E2_NUM     :=cNUM
			E2_PARCELA :=cPARCEL
			E2_TIPO    :='PR'
			E2_NATUREZ :=TRB->E2_NATUREZ                 //E2_CODCONT|E2_PORTADO|
			E2_FORNECE :=TRB->E2_FORNECE
			E2_LOJA    :=TRB->E2_LOJA
			E2_NOMFOR  :=TRB->E2_FORNECE
			E2_EMISSAO :=DATE()
			E2_VENCTO  :=dVENCTO
			E2_VENCREA :=dVENCTO
			E2_VALOR   :=nVALOR                         //|E2_ISS|E2_IRRF|E2_NUMBCO|E2_INDICE|E2_BAIXA|E2_BCOPAG|
			E2_EMIS1   :=DATE()
			E2_HIST    :='PRV '+ALLTRIM(TRB->ED_DESCRIC)//|E2_LA|E2_LOTE|E2_MOTIVO|E2_MOVIMEN|E2_OP|E2_OK|
			E2_SALDO   :=nVALOR                         //|E2_DESCONT|E2_MULTA|E2_JUROS|E2_CORREC|E2_VALLIQ|E2_VENCORI|E2_VALJUR|E2_PORCJUR|
			E2_MOEDA   :=1                              //|E2_NUMBOR|E2_FATPREF|E2_FATURA|E2_PROJETO|E2_CLASCON|E2_RATEIO|E2_DTVARIA|E2_VARURV|
			E2_VLCRUZ  :=nVALOR                         //|E2_DTFATUR|E2_ACRESC|E2_TITORIG|E2_PARCIR|E2_ARQRAT|E2_IMPCHEQ|E2_OCORREN|E2_IDENTEE|E2_FLUXO|E2_ORIGEM|E2_PARCISS|E2_ORDPAGO|E2_DESDOBR|E2_PARCINS|E2_INSS|E2_APROVA|E2_FLAGFAT|E2_DATALIB|E2_TIPOFAT|E2_ANOBASE|E2_MESBASE|E2_SDACRES|E2_DECRESC|E2_SDDECRE|E2_USUALIB|E2_NUMTIT|E2_MULTNAT|E2_PROJPMS|E2_PLLOTE|E2_CODRET|E2_DIRF|E2_TXMOEDA|E2_MODSPB|E2_IDCNAB|E2_PARCCSS|E2_RETENC|E2_TITCSLL|E2_VRETPIS|E2_VRETCOF|E2_VRETCSL|E2_PRETPIS|E2_PRETCOF|E2_PRETCSL|E2_SEQBX|E2_BASEPIS|E2_BASECOF|E2_BASECSL|E2_NUMLIQ|E2_BCOCHQ|E2_AGECHQ|E2_CTACHQ|E2_CONTAD|E2_CODORCA|E2_SEST|E2_PARCSES|E2_FILDEB|E2_FILORIG|E2_FORNISS|E2_LOJAISS|E2_DEBITO|E2_CCD|E2_ITEMD|E2_CLVLDB|E2_CREDIT|E2_CCC|E2_ITEMC|E2_CLVLCR|E2_COFINS|E2_PIS|E2_CSLL|E2_PARCCOF|E2_PARCPIS|E2_PARCSLL|E2_TITPIS|E2_TITCOF|E2_TITCSL|E2_TITINS|E2_CODBAR|E2_VRETISS|E2_VENCISS|E2_VBASISS|E2_MDRTISS|E2_VARIAC|E2_PERIOD|E2_MDCONTR|E2_MDREVIS|E2_MDPLANI|E2_MDCRON|E2_MDPARCE|E2_FRETISS|E2_TXMDCOR|E2_APLVLMN|E2_CLEARIN|E2_HORASPB|E2_PRETIRF|E2_SEFIP|E2_TRETISS|E2_VRETIRF|E2_PLOPELT|E2_CODRDA|E2_PARCFET|E2_FETHAB|E2_FORORI|E2_LOJORI|E2_STATUS|E2_DTDIRF|E2_INSSRET|E2_CODAGL|E2_PARCAGL|E2_CODRCOF|E2_CODRCSL|E2_CODRPIS|E2_DTBORDE|E2_TIPOLIQ|E2_USERLGI|E2_USERLGA|E2_BASEIRF|E2_FATFOR|E2_FATLOJ|E2_TITPAI|E2_TITADT|E2_PROCPCC|E2_FORNPAI|E2_NODIA|E2_VRETINS|E2_PRETINS|E2_IDDARF|D_E_L_E_T_|R_E_C_N_O_|R_E_C_D_E_L_|E2_DATAAGE|E2_USUASUS|E2_USUACAN|E2_DATASUS|E2_DATACAN|E2_LIMCAN|E2_BASEINS|E2_BASEISS|E2_TEMDOCS|E2_FACS|E2_PARCFAC|E2_PARCFAB|E2_FABOV|E2_CODISS|E2_DIACTB|E2_CIDE|E2_RETCNTR|E2_MDDESC|E2_MDBONI|E2_MDMULT|E2_CODINS|E2_PARCCID|E2_CODAPRO|E2_STATLIB|E2_PARIMP5|E2_MSIDENT|E2_PARIMP3|E2_PARIMP1|E2_PARIMP4|E2_PARIMP2|E2_PRISS|E2_PRINSS|E2_NUMPRO|E2_INDPRO|E2_AGLIMP|E2_PREOP|E2_IDMOV|E2_RATFIN|E2_NUMSOL|E2_CODOPE|E2_FIMP|E2_NFELETR|E2_FAMAD|E2_PARCFAM|E2_FMPEQ|E2_PARCFMP|E2_FORBCO|E2_FORAGE|E2_FAGEDV|E2_FORCTA|E2_FCTADV|E2_TPDESC|E2_FUNDESA|E2_IMAMT|E2_FASEMT|E2_PARFUND|E2_PARIMA|E2_PARFASE|E2_RETINS|E2_DOCHAB|E2_LINDIG|E2_DTAPUR|E2_NROREF|E2_NOMERET|E2_TPINSC|E2_CCUSTO|E2_FORMPAG|E2_TPESOC|E2_CLVL|E2_ITEMCTA|E2_CNPJRET|E2_CNO
			
			SE2->(MsUnlock())
		ENDIF
		TR2->(DbCloseArea())
		TRB->(DBSKIP())
	ENDDO
NEXT

TRB->(DbCloseArea())

///MSGALERT('FIM CADASTRO SE2','Atencao')

RESET ENVIRONMENT

Return

