#include "rwmake.ch"
#include "topconn.ch"

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณCADSX5    บAutor  ณMarco Aurelio        บ Data ณ  12/10/18  บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ Cadastro de Tabelas do SX5                                 บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ DOMEX                                                      บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/

User Function CADSX5()



U_MRSSX5('60','Cod. Servicos' )
/*

//Local aCores :=  {}
Private cAlias := "SX5"

DbSelectArea(cAlias)
aRotina := {}

//AADD(aRotina,{ "Pesquisar       ",'AxPesqui'            , 0, 1 } )
//AADD(aRotina,{ "Visualizar      ",'AxVisual'            , 0, 2 } )
AADD(aRotina,{ "21 - Tritutacao ","U_MRSSX5('21','Grupo Tributacao' "  , 0, 3 } )  
AADD(aRotina,{ "60 - Servicos   ","U_MRSSX5('60','Cod.Servico' "  , 0, 3 } )

//AADD(aRotina,{ "Alterar         ","U_"+cAlias+"ALTERA"  , 0, 4 } )
//AADD(aRotina,{ "Excluir         ","U_"+cAlias+"DELETA"  , 0, 5 } )
//AADD(aRotina,{ "Filtrar         ","U_"+cAlias+"FILTRO"  , 0, 3 } )
//AADD(aRotina,{ "Legenda         ","U_fLeg"+cAlias       , 0, 7 } )

//cCadastro := "Manuten็ใo de Tabelas - SX5"


//mBrowse( 6, 1,22,75,cAlias,,,,,,aCores              ,,,,,,,,) 
mBrowse( 6, 1,22,75,cAlias,,,,,,              ,,,,,,,,) 
*/
Return
