#INCLUDE "Protheus.ch"
#INCLUDE "Rwmake.ch"
#include "TbiConn.ch"
#include "TbiCode.ch"
#DEFINE ENTER Chr(13)+Chr(10)
/*/
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNOVO4     บ Autor ณ AP6 IDE            บ Data ณ  12/01/05   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDescricao ณ Codigo gerado pelo AP6 IDE.                                บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP6 IDE                                                    บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
/*/

User Function BOTAO()
Local nLin := 020
Local nPos := 001    

PREPARE ENVIRONMENT EMPRESA "01" FILIAL "01" MODULO "FAT"

DEFINE MSDIALOG oDlga TITLE OemToAnsi("BMP") From 9,0 To 28,80 //OF oMainWnd
      
	@ nLin,nPos BUTTON "01" SIZE 40,15 ACTION Btn("01") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "02" SIZE 40,15 ACTION Btn("02") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "03" SIZE 40,15 ACTION Btn("03") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "04" SIZE 40,15 ACTION Btn("04") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "05" SIZE 40,15 ACTION Btn("05") PIXEL OF oDlga
	nLin += 20  
	nPos := 001

	@ nLin,nPos BUTTON "06" SIZE 40,15 ACTION Btn("06") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "07" SIZE 40,15 ACTION Btn("07") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "08" SIZE 40,15 ACTION Btn("08") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "09" SIZE 40,15 ACTION Btn("09") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "10" SIZE 40,15 ACTION Btn("10") PIXEL OF oDlga
	nLin += 20  
	nPos := 001

	@ nLin,nPos BUTTON "11" SIZE 40,15 ACTION Btn("11") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "12" SIZE 40,15 ACTION Btn("12") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "13" SIZE 40,15 ACTION Btn("13") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "14" SIZE 40,15 ACTION Btn("14") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "15" SIZE 40,15 ACTION Btn("15") PIXEL OF oDlga
	nLin += 20  
	nPos := 001

	@ nLin,nPos BUTTON "16" SIZE 40,15 ACTION Btn("16") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "17" SIZE 40,15 ACTION Btn("17") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "18" SIZE 40,15 ACTION Btn("18") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "19" SIZE 40,15 ACTION Btn("19") PIXEL OF oDlga
    nPos += 050
	@ nLin,nPos BUTTON "20" SIZE 40,15 ACTION Btn("20") PIXEL OF oDlga

ACTIVATE MSDIALOG oDlga ON INIT Eval({ || EnchoiceBar(oDlga,{||oDlga:End()},.T.,)  }) CENTERED

//RESET ENVIRONMENT
Return           


/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณBMP2      บAutor  ณMicrosiga           บ Data ณ  02/27/10   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/

Static Function Btn(n)
Local aBotoes := {"ABRIRCX","ACDIMG16","ACDIMG32","ADDCONTAINER","ADD_RADAR","ADICIONAR_001","AFASTAMENTO","AFASTAME_MDI","AFVIMG16",;
"AFVIMG32","AGEIMG16","AGEIMG32","AGENDA","AGRIMG16","AGRIMG32","ALTERA","ALT_CAD","AMARELO","ANALITIC","ANALITICO","APDIMG16",;
"APDIMG32","ANALITICO_MDI","ANALITIC_MDI","APTIMG16","APTIMG32","AREA","ARMAZEM","ARMIMG16","ARMIMG32","ART_ESP_MELHORIA",;
"ART_ESP_RISCO","ART_PAD_ANOTACAO","ART_PAD_DADOS","ART_PAD_GRUPO","ATALHO","ATFIMG16","ATFIMG32","AUTOM","AUTORIZ","AVANCAR",;
"AVANCAR_MDI","AVANCAR2","AVANCAR2_OCEAN","AVANCAR_OCEAN","AVGARMAZEM","AVGBOX1","AVGLBPAR1","AVGOIC1","AVG_DOC_VIEW","AVG_ENV_VIEW",;
"AVG_PREF","AVG_SRV_VIEW","AVG_VIEW","AVIAO","AZUL","BACKGROUNDBLACK","BACKGROUNDBLACKLOTUS","BACKGROUNDBLUE","BAHEAD","BAIXATIT",;
"BALANCA","BAR","BBEARLEFT","BBEARRIGHT","BEMVINDOPORT_MDI","BEMVINDOVAZIO_MDI","BEND","BG","BGCOLOR","BGFWSPLITER","BG_1","BG_BACKLOGO",;
"BG_SPLIT","BG_TITLE","BIG3","BKEEPLEFT","BKEEPRIGHT","BLEFT","BMPCALEN","BMPCONS","BMPCPO","BMPDEL","BMPEMERG","BMPGROUP",;
"BMPINCLUIR","BMPORD","BMPORD1","BMPORD2","BMPPARAM","BMPPERG","BMPPOST","BMPSDOC","BMPSEP1","BMPSEP2","BMPSEP3","BMPSERV1","BMPSERV2",;
"BMPSXB","BMPSXG","BMPTABLE","BMPTGR","BMPUSER","BMPVISUAL","BMPVISUAL16","BOMB","BOMBE","BONUS1","BONUS_MDI","BOOM","BORDA_PANEL","BORDA_REPORT",;
"BORDER1","BORDER1WFMENU","BORDER2","BORDER2WFMENU","BORDER3WFMENU","BOTTOM","BPM16","BPM32","BPMIMG16","BPMIMG32","BPMSDOCA","BPMSDOCE","BPMSDOCI",;
"BPMSEDT1","BPMSEDT1A","BPMSEDT1E","BPMSEDT1I","BPMSEDT2","BPMSEDT2A","BPMSEDT2E","BPMSEDT2I","BPMSEDT3","BPMSEDT3A","BPMSEDT3E","BPMSEDT3I","BPMSEDT4",;
"BPMSEDT4A","BPMSEDTE","BPMSEDT4I","BPMSREC","BPMSRECA","BPMSRECE","BPMSRECI","BPMSRELAA","BPMSRELAE","BPMSRELAI","BPMSTSK1A","BPMSTSK1E","BPMSTSK1I",;
"BPMSTSK2A","BPMSTSK2E","BPMSTSK2I","BPMSTSK3A","BPMSTSK3E","BPMSTSK3I","BPMSTSK4A","BPMSTSK4E","BPMSTSK4I","BPM_ICO_ADICIONAR","BPM_ICO_CHK","BPM_ICO_COPIAR","BPM_ICO_CORES",;
"BPM_ICO_DELETAR","BPM_ICO_EDITAR","BPM_ICO_FECHAR","BPM_ICO_FORMULARIO","BPM_ICO_GRAVAR","BPM_ICO_LAYOUT","BPM_ICO_OK","BPM_ICO_RELACIONAR","BPM_ICO_SAIR","BPM_ICO_USUARIOS",;
"BPM_ICO_ZOOM_MAIS","BPM_ICO_ZOOM_MENOS","BRIGHT","BRW_CONFIG","BRW_FILTRO","BRW_FIND","BRW_LUPA","BRW_PRINT","BR_AMARELO","BR_AMARELO_OCEAN","BR_AZUL","BR_AZUL_OCEAN",;
"BR_BRANCO","BR_BRANCO_OCEAN","BR_CANCEL","BR_CINZA","BR_CINZA_OCEAN","BR_LARANJA","BR_LARANJA_OCEAN","BR_MARROM","BR_MARROM_OCEAN","BR_PINK","BR_PINK_OCEAN",;
"BR_PRETO","BR_PRETO_OCEAN","BR_VERDE","BR_VERDE_OCEAN","BR_VERMELHO","BR_VERMELHO_OCEAN","BR_VIOLETA","BSPESQUI","BSTART","BTCALC","BT_CALC_MDI",;
"BTCALEND","BTCALEND_MDI","BTCLOSEFWSPLITER","BTCLOSEWINDOW","BTOPENFWSPLITER","BTPESQ","BTURNSHARPLEFT","BTURNSHARPRIGHT","BUDGET","CADEADO","CALCULADORA",;
"CANCELPRINT_OCEAN","CANCEL_15","CANCEL_CHILD_15","CANCEL_MDI","CANCEL_OCEAN","CARGASEQ","CCTCALC","CDAIMG16","CDAIMG32","CELERINA","CFGIMG16",;
"CFGIMG32","CFGPANEL","CHAT","CHAVE2","CHECKED","CHECKED_CHILD_15","CHECKED_CHILD_25","CHECKED_MASTER_15","CHECKED_MASTER_25","CLEANBORDERWHITE","CLIENTE",;
"CLIPS","CLIPS_PQ","CLOCK01","CLOCK02","CLOCK03","CLOCK04","CLOSE","COBROWSR","COIMG32_OCEAN","COLFORM","COLOR","COLTOT","COLTOT16","COMIMG16","COMIMG32",;
"COMPTITL","COMSOM","CONIMG16","CONIMG32","CONTAINR","CONX_ASSOCIACAO","CONX_MENSAGEM","CONX_SEQUENCIA","CONX_SEQUENCIA_CONDICIONAL","CONX_SEQUENCIA_PADRAO","COPYUSER","COSTUMER",;
"CRDIMG16","CRDIMG32","CREDITO16","CREDITOPB16","CRITICA","CRMIMG16","CRMIMG32","CSAIMG16","CSAIMG32","CSSBTN","CSSBTNFOCUS","CSSBTNIMAGE","CSSBTNIMAGEFOCUS","CSSBTNSCROLL",;
"CSSBTNSCROLLFOCUS","CSSFOLDER","CSSFOLDER2","CSSFOLDER3","CSSFOLDER4","CSSFOLDER5","CSSGET","CSSGETFOCUS","CSSRADIO","CSSRADIOCHECKED","CSSRADIOOVER","CSSPLIT","CSSWIDGETSCROLL",;
"CSSWIDGETSCROLL1","CSSWIDGETSCROLL2","CSSWIDGETSCROLL3","CSSWIDGETSCROLL4","CSSWIDGETSCROLL5","CSSWIDGETSCROLL6","CTBIMG16","CTBIMG32","CTBLANC","CTBREPLA","DARKBORDERBLACK",;
"DARKBORDERBLACKFOCUS","DARKBORDERBLACKOVER","DARKBORDERBLUE","DARKBORDERBLUEFOCUS","DARKBORDERWHITE","DARKBORDERWHITEFOCUS","DBG03","DBG05","DBG06","DBG07","DBG09","DBG10",;
"DBG12","DEBITO16","DEBITOPB16","DEB_CRED16","DEFAULTBORDERWHITE","DEFAULTBORDERWHITEOVER","DEGRADE_FWMENU","DEGRADE_HMBROWSE","DELWEB","DEPENDENTES","DESTINOS","DESTINOS2",;
"DEVOLNF","DISABLE","DISCAGEM","DISCOUNT","DOWN","ECOIMG16","ECOIMG32","EDCIMG16","EDCIMG32","EDIT","EDITABLE","EDITWEB","EECIMG16","EECIMG32","EFFIMG16","EFFIMG32",;
"EICIMG16","EICIMG32","EMAIL","EMPILHADEIRA","ENABLE","ENGRENAGEM","ENGRENAGEM17","ENSAIO","ESCALA","ESTIMG16","ESTIMG32","ESTOMOVI","EXCLITEM","EXCLUIR","EXECUTEBORDERWHITE","F10_AMAR",;
"F10_AZUL","F10_CINZ","F10_LARA","F10_MARR","F10_NULL","F10_PINK","F10_PRET","F10_VERD","F10_VERM","FASIMG16","FASIMG32","FERIAS","FERRAM","FILTRO","FILTRO1",;
"FINAL","FINIMG16","FINIMG32","FISIMG16","FISIMG32","FOLDER10","FOLDER11","FOLDER12","FOLDER13","FOLDER14","FOLDER15","FOLDER5","FOLDER516","FOLDER6","FOLDER616",;
"FOLDER7","FOLDER8","FOLDER9","FORD","FORM","FRCOLOR","FRONT","FRTIMG16","FRTIMG32","FRTOFFLINE","FRTONLINE","FRTONLIN","FUNDOBTN","FUNDOBTNFOLDER","GACIMG16","GACIMG32",;
"GADGET_LOGO","GAVIMG16","GAVIMG32","GCTIMG16","GCTIMG32","GEO","GEOEMAIL","GEOROTA","GEOTRECHO","GERPROJ","GER_BG1","GER_BTN_CANC","GER_CANC_AMARELO","GER_CANC_LARANJA","GER_CANC_PRETO",;
"GER_CANC_VERMELHO","GER_ICO_FERRAMENTAS","GER_ICO_PROCESSO","GER_ICO_SUBPROCESSO","GER_TAREFA_EMEXEC","GER_TAREFA_PEND","GLOBO","GM","GOBOTTOM","GOTOP","GPEIMG16","GPEIMG32","GRPIMG16","GRPIMG32",;
"GRAF2D","GRAF3D","HANDHELP","HELP","HEOIMG16","HEOIMG32","HISTORIC","HSPIMG16","HSPIMG32","ICEIMG16","ICEIMG32","ICONE","ICONE_TABELA","ICONE_TABELA_BLOQUEADO","ICONE_TABELA_PRINCIPAL",;
"ICONMODULOS","IC_17","IC_ART_PAD_ANOTACAO","IC_ART_PAD_DADOS","IC_OBJ_ATV_ATIVIDADE","IC_OBJ_ATV_ATIVIDADE_TIMER","IC_OBJ_ATV_LOOPING","IC_OBJ_ATV_SUBP_LOOPING","IC_OBJ_ATV_SUBP_PROCESSO","IC_OBJ_EVTO_FINAL",;
"IC_OBJ_EVTO_INICIO","IC_OBJ_EVTO_INICIO_MENSAGEM","IC_OBJ_EVTO_INICIO_TIMER","IC_OBJ_EVTO_INTERMEDIARIO","IC_OBJ_EVTO_INTERMEDIARIO_MENSAGEM","IC_OBJ_EVTO_INTERMEDIARIO_TIMER","IC_OBJ_GAT_AND",;
"IC_OBJ_GAT_XOR","IMAGE_LUPA","IMPORT","IMPORT_TABLE","IMPRESSAO","IMPRESSAO16","IMP_FISC","INDICATORACTIONACTIVE","INDICATORACTIONINACTIVE","INDICATORCHECKBOX","INDICATORCHECKBOXCHACKED","INDICATORCHECKBOXOVER","INDICATORCHECKOFFVISTA",;
"INDICATORCHECKONVISTA","INDICATORRADIOOFFVISTA","INDICATORRADIOONVISTA","INSTRUME","KEY0","KEY1","KEY1NUM","KEY2","KEY2NUM","KEY3","KEY3NUM","KEY4","KEY4NUM","KEY5","KEY5NUM",;
"KEY6","KEY6NUM","KEY7","KEY7NUM","KEY8","KEY8NUM","KEY9","KEY9NUM","KEYA","KEYB","KEYBACKSPACE","KEYC","KEYCAPS_ON","KEYCAPS_OFF","KEYD",;
"KEYDEL","KEYE","KEYENTER","KEYESC","KEYF","KEYG","KEYH","KEYI","KEYJ","KEYK","KEYL","KEYM","KEYN","KEYO","KEYP","KEYPONTO","KEYPONTONUM","KEYQ",;
"KEYR","KEYS","KEYSHIFT_OFF","KEYSHIFT_ON","KEYSOMA","KEYSPACE","KEYT","KEYU","KEYV","KEYIRGULA","KEYVIRGULANUM","KEYW","KEYY","KEYZ","LANDSCAPE",;
"LAUDO","LBNO","LBOK","LBTICK","LBTIK","LEFT","LEITURAX","LIGHTBLU","LIMPEZA","LINE","LIQCHECK","LJPRECO","LOCALIZA","LOGIN","LOGO","LOGOEMPTY",;
"LOGOPYME","LOGOSIGA","LOGOTOTVS","LOGOTOVS","LOJAWIN","LOJIMG16","LOJIMG32","LUPA","LVEIMG16","LVEIMG32","MAIS","MAQFOTO","MATERIAL","MAXIMIZE","MDIEXCEL",;
"MDIHELP","MDILOGOFF","MDIRUN","MDISPOOL","MDIVISIO","MDTIMG16","MDTIMG32","MENOS","MENUINDICATOR","MENURUN","MESSENGER","METAS_BAIXO_16","METAS_BAIXO_LEG","METAS_CIMA_16",;
"METAS_CIMA_LEG","MINIECF","MINIMIZE","MNTIMG16","MNTIMG32","MPWIZARD","MSGFORWD","MSGHIGH","MSGREPLY","MSMDILOGO","NAOCONFO","NCO","NEWWEB","NEXT",;
"NGOSAMARELO","NGOSVERDE","NGOSVERMELHO","NGSETAUPLEFT","NGSSAMARELO","NGSSVERDE","NGSSVERMELHO","NG_CALOTA","NG_ICO_ALTBEM","NG_ICO_ALTBEMM","NG_ICO_ALTID","NG_ICO_ALTIDM","NG_ICO_ALTSS",;
"NG_ICO_ALTSSM","NG_ICO_DSS","NG_ICO_DSSM","NG_ICO_ETAPA","NG_ICO_EXCBEM","NG_ICO_EXCID","NG_ICO_EXCIDM","NG_ICO_EXCSS","NG_ICO_EXCSSM","NG_ICO_FERRAM","NG_ICO_FILTRO",;
"NG_ICO_FINAL","NG_ICO_FINSS","NG_ICO_HISTORICO","NG_ICO_IMP","NG_ICO_INCBEM","NG_ICO_INCBEMM","NG_ICO_INCID","NG_ICO_INCIDM","NG_ICO_INCOS","NG_ICO_INCSS",;
"NG_ICO_INCSSM","NG_ICO_IOSCO","NG_ICO_IOSCOM","NG_ICO_IOSPR","NG_ICO_IOSPRM","NG_ICO_LEGENDA","NG_ICO_LGDD","NG_ICO_LGDH","NG_ICO_OCOR","NG_ICO_RELAC","NG_ICO_RETORNO01",;
"NG_ICO_RETORNO02","NG_ICO_RETORNO03","NG_ICO_RETORNO04","NG_ICO_RETOS","NG_ICO_RETOSM","NG_ICO_VISUAL","NG_ICO_VISUALIZAR","NG_OS_MARCADA","NG_OS_TROCA","NG_PNEU_PRETO_CLARO_1",;
"NG_PNEU_PRETO_CLARO_2","NG_PNEU_PRETO_ESCURO_1","NG_PNEU_PRETO_ESCURO_2","NG_RODADOS_ANALISE","NG_RODADOS_ESTOQUE","NG_RODADOS_PLACA","NG_RODADOS_RECAPE","NG_RODADOS_SUCATA",;
"NOCHECKED","NOCHECKED_15","NOCHECKED_CHILD_15","NOCHECKED_CHILD_25","NOCHECKED_MASTER_15","NOCHECKED_MASTER_25","NOCONNECT","NONE_15","NORMAS","NOTE","NOTE_PQ","NOVACELULA",;
"OBJETIVO","OCUPACAO","OFIIMG16","OFIIMG32","OK","OK_15","OK_CHILD","OMSDIVIDE","OMSIMG16","OMSIMG32","OPEN","OPENCLOSING","OPERACAO","ORDEM","ORGIMG16","ORGIMG32",;
"OUTLOOK","PAPEL_ESCRITO","PAPIMG16","PAPIMG32","PARAINICIAL","PARAMETROS","PCOANTES","PCOBCOBD","PCOCO","PCOCUBE","PCODEPOI","PCOENTRE","PCOFXCANCEL","PCOFXOK","PCOIMG16",;
"PCOIMG32","PCOIMPR2","PCOIMPRESS","PCOPER_1","PCOPOSIT","PCOPRTLAN","PCOPRTPOR","PCOSPOOL","PCOTODOS","PCO_COINC","PCO_CONOR","PCO_ITALT","PCO_ITEXC","PCPIMG16",;
"PCPIMG32","PECIMG16","PECIMG32","PEDIDO","PENDENTE","PESQUISA","PGDOWN","PGNEXT","PGPREV","PGREDT","PGUP","PHOIMG16","PHOIMG32","PIN","PLAY","PLNPROP","PLSIMG16",;
"PLSIMG32","PMSCOLOR","PMSDOC","PMSEDT3","PMSEDT4","PMSEXPALL","PMSEXPCMP","PMSIMG16","PMSIMG32","PMSINFO","PMSMAIS","PMSMATE","PMSMENOS","PMSPESQ","PMSPRINT","PMSRELA",;
"PMSRRFSH","PMSSETABOT","PMSSETADIR","PMSSETADOWN","PMSSETAESQ","PMSSETATOP","PMSSETAUP","PMSSUPE","PMSTASK1","PMSTASK116","OMSTASK2","PMSTASK3","PMSTASK4","PMSTASK5",;
"PMSTASK6","PMSUPDOWN","PMSZOOMIN","PMSZOOMOUT","PNEU2","PONIMG16","PONIMG32","POSCLI","PRECO","PREDIO","PREV","PREV_PQ","PRINT02","PRINT03","PROCESSA","PRODUT2","PRODUTO","PROJETPMS",;
"PROTHEUSREPORT","PRTETQ","PSEARCH","PUZZLE","QADIMG16","QADIMG32","QDOIMG16","QDOIMG32","QIEIMG16","QIEIMG32","QIPIMG16","QIPIMG32","QMTIMG16","QMTIMG32","QMT_COND","QMT_NO",;
"QMT_OK","QNCIMG16","QNCIMG32","QTDREJ","RADAR","RECALC","RECORRENTE","RECORTAR","REDUCAOZ","RELACIONAMENTO_DIREITA","RELACIONAMENTO_DIREITA_PQ","RELATORIO","RELOAD","REPIMG16","REPIMG32",;
"REPOSIT","RESPADEX","RESPONSA","RIGHT","ROSA","ROTEIRO","RPMCABEC","RPMCPO","RPMDES","RPMFORM","RPMFUNC","RPMGROUP","RPMIMG16","RPMIMG32","RPMIMP","RPMNEW","RPMNEW2",;
"RPMOPEN","RPMPERG","RPMSAVE","RPMTABLE","RSPIMG16","RSPIMG32","S4SB014N","S4WB005N","S4WB005N_PQ","S4WB006N","S4WB007N","S4WB007N_PQ","S4WB008N","S4WB009N","S4WB010N","S4WB011N",;
"S4WB013N","S4WB014A","S4WB014B","S4WB016N","S4WB018N","S4WB019N","S4WB020N","S4WB021N","S4WB022N","S4WB050N","S4WB051N","S4WB052N","S4WB053N","S4WB054N","S4WB055N",;
"S4WB056N","S4WB057N","S4WB058N","S4WB059N","S4WB060N","S4WB061N","S4WB062N","S4WB063N","S4WB064N","S4WB065N","SA","SALARIOS","SALVAR","SAVELOCK","SDUADDTBL","SDUAPPEND",;
"SDUCLOSE","SDUCOPYTO","SDUCOUNT","SDUCREATEIDX","SDUCUSTOM","SDUDELETE","SDUDELREC","SDUDRPTBL","SDUEDIT","SDUERASE","SDUFIELDS","SDUFILTER","SDUFIND","SDUGOTO","SDUIMPORT",;
"SDUNEW","SDUOPEN","SDUOPENIDX","SDUORDER","SDUOTHER","SDUPACK","SDUPROP","SDUPROPR","SDURECALL","SDUREPL","SDUSEEK","SDUSETDEL","SDUSOFTSEEK","SDUSTRUCT","SDUSUM","SDUSUM16",;
"SDUZAP","SELECT","SELECTALL","SEMSOM","SEM_RELACIONAMENTO_DIREITA","SEM_RELACIONAMENTO_ESQUERDA","SEPGROUP","SEPGROUP1","SEPGROUP2","SEPGROUP3","SEPGROUP4","SEPGROUP5","SEPITENS",;
"SETASCROLL","SETA_DOWN","SETA_UP","SGAIMG16","SGAIMG32","SHAPE01","SHAPE02","SHAPE03","SHAPE04","SHAPE05","SHORTCUTMINUS","SHORTCUTPLUS","SIGACRM16","SIGACRM32","SIGAECO16","SIGAECO32",;
"SIGAEFF16","SIGAEFF32","SIGALVE16","SIGALVE32","SIGAPHOTO16","SIGAPHOTO32","SIMULACA","SOLICITA","SOLUCOESPORT_MDI","SSFONTES","STOP","STOPALL","SUGESTAO","SUMARIO","SVM","SWIN_LANE",;
"SWIN_POOL","TAB1","TABPRICE","TCFIMG16","TCFIMG32","TECIMG16","TECIMG32","TELABLUR","TELA_LOGIN_05","TELA_LOGIN_08","TELA_LOGIN_13","TELA_LOGIN_14","TESTE","TITLE","TK_ALTFIN","TK_FIND",;
"TK_FONE","TK_HISTORY","TK_NOVO","TK_REFRESH","TK_VERTIT","TMKIMG16","TMKIMG32","TOOLBAR_MDI","TOP","TPOPAGT01","TRIDOWN","TRILEFT","TRIRIGHT","TRIUP","TRMIMG16","TRMIMG32","TROCO","UNCHECKED",;
"UNSELECTALL","UP","UPDERROR","UPDERROR17","UPDERROR50","UPDINFORMATION","UPDWARNING","UPDWARNING17","UPDWARNING50","VEIIMG16","VEIIMG32","VENDEDOR","VERNOTA","VOLTAR","WALKTHROUGH","WALKTHROUGH16",;
"WALKTHROUGH32","WATCH","WEB","WFCHK","WFUNCHK","WMSIMG16","WMSIMG32","WORD","X","XCLOSE","AFASTAME","APLOGO","BAIXATIT","BEMVINDO","BUDGETY","CARGA","CARGANEW","CGETFILE_0","CGETFILE_1","CGETFILE_2",;
"CGETFILE_3","CGETFILE_4","WIZARD","CGETFILE_5","CGETFILE_6","CGETFILE_7","CGETFILE_8","CGETFILE_9","CGETFILE_10","CHAT","CHAT1","CHAT2","CHECKOK","COLAR","COLDEL","COLGERA","COLINC","COPIA","COPIAR",;
"DBG3","DELETE","DEPENDEN","GROUP","LEFT2","MEDEXT","NOMEDICA","NOVACELU","PMSTOOLS","PORTRAIT","PRINT","RIGHT2","RPMIMPORT","S4WB001N","S4WB004N","S4WB014N","SHORTCUTDEL","SHORTCUTEDIT","SHORTCUTNEW",;
"SVD","TPOPAGTO","USER"}

Local k:= IIf(n=="01",1,(Val(n)*53)+1)
Local nItem := k+53
Local nLin2 := 010
Local nPos2 := 005
Local cRegra:= ""


DEFINE MSDIALOG oDlgb TITLE OemToAnsi("BMP") From 9,0 To 58,125 //OF oMainWnd
cMensagem := " Desenvolvido por Paulo Bindo"+ENTER
cMensagem += " Site www.supeerp.com"

//nconta:= 1
For k:=k To nItem
	If nItem <= Len(aBotoes)
	@ nLin2,nPos2 BITMAP ResName aBotoes[k] OF oDlgb Size 15,15 ON CLICK (MsgInfo(cMensagem))  NoBorder  Pixel
//	nLin2+= 16

//	cRegra += "@"+ StrZero(nLin2,3)+","+StrZero(nPos2,3)+" Say aBotoes[k+"+strzero(nconta,3)+"] OF oDlgb Size 90,15 Pixel"+ENTER
//	nconta++
//    nLin2-= 16
	If nPos2 > 450 
		nLin2 += 30  
		nPos2 := 005
	Else
	    nPos2 += 100
	EndIf
	Else
	aAdd(aBotoes,"")	                
	EndIf
Next
//MEMOWRITE("REGRA.TXT",CREGRA)  
k:= IIf(n=="01",1,(Val(n)*53))
@026,005 Say aBotoes[k+001] OF oDlgb Size 90,15 Pixel
@026,105 Say aBotoes[k+002] OF oDlgb Size 90,15 Pixel
@026,205 Say aBotoes[k+003] OF oDlgb Size 90,15 Pixel
@026,305 Say aBotoes[k+004] OF oDlgb Size 90,15 Pixel
@026,405 Say aBotoes[k+005] OF oDlgb Size 90,15 Pixel
@026,505 Say aBotoes[k+006] OF oDlgb Size 90,15 Pixel
@056,005 Say aBotoes[k+007] OF oDlgb Size 90,15 Pixel
@056,105 Say aBotoes[k+008] OF oDlgb Size 90,15 Pixel
@056,205 Say aBotoes[k+009] OF oDlgb Size 90,15 Pixel
@056,305 Say aBotoes[k+010] OF oDlgb Size 90,15 Pixel
@056,405 Say aBotoes[k+011] OF oDlgb Size 90,15 Pixel
@056,505 Say aBotoes[k+012] OF oDlgb Size 90,15 Pixel
@086,005 Say aBotoes[k+013] OF oDlgb Size 90,15 Pixel
@086,105 Say aBotoes[k+014] OF oDlgb Size 90,15 Pixel
@086,205 Say aBotoes[k+015] OF oDlgb Size 90,15 Pixel
@086,305 Say aBotoes[k+016] OF oDlgb Size 90,15 Pixel
@086,405 Say aBotoes[k+017] OF oDlgb Size 90,15 Pixel
@086,505 Say aBotoes[k+018] OF oDlgb Size 90,15 Pixel
@116,005 Say aBotoes[k+019] OF oDlgb Size 90,15 Pixel
@116,105 Say aBotoes[k+020] OF oDlgb Size 90,15 Pixel
@116,205 Say aBotoes[k+021] OF oDlgb Size 90,15 Pixel
@116,305 Say aBotoes[k+022] OF oDlgb Size 90,15 Pixel
@116,405 Say aBotoes[k+023] OF oDlgb Size 90,15 Pixel
@116,505 Say aBotoes[k+024] OF oDlgb Size 90,15 Pixel
@146,005 Say aBotoes[k+025] OF oDlgb Size 90,15 Pixel
@146,105 Say aBotoes[k+026] OF oDlgb Size 90,15 Pixel
@146,205 Say aBotoes[k+027] OF oDlgb Size 90,15 Pixel
@146,305 Say aBotoes[k+028] OF oDlgb Size 90,15 Pixel
@146,405 Say aBotoes[k+029] OF oDlgb Size 90,15 Pixel
@146,505 Say aBotoes[k+030] OF oDlgb Size 90,15 Pixel
@176,005 Say aBotoes[k+031] OF oDlgb Size 90,15 Pixel
@176,105 Say aBotoes[k+032] OF oDlgb Size 90,15 Pixel
@176,205 Say aBotoes[k+033] OF oDlgb Size 90,15 Pixel
@176,305 Say aBotoes[k+034] OF oDlgb Size 90,15 Pixel
@176,405 Say aBotoes[k+035] OF oDlgb Size 90,15 Pixel
@176,505 Say aBotoes[k+036] OF oDlgb Size 90,15 Pixel
@206,005 Say aBotoes[k+037] OF oDlgb Size 90,15 Pixel
@206,105 Say aBotoes[k+038] OF oDlgb Size 90,15 Pixel
@206,205 Say aBotoes[k+039] OF oDlgb Size 90,15 Pixel
@206,305 Say aBotoes[k+040] OF oDlgb Size 90,15 Pixel
@206,405 Say aBotoes[k+041] OF oDlgb Size 90,15 Pixel
@206,505 Say aBotoes[k+042] OF oDlgb Size 90,15 Pixel
@236,005 Say aBotoes[k+043] OF oDlgb Size 90,15 Pixel
@236,105 Say aBotoes[k+044] OF oDlgb Size 90,15 Pixel
@236,205 Say aBotoes[k+045] OF oDlgb Size 90,15 Pixel
@236,305 Say aBotoes[k+046] OF oDlgb Size 90,15 Pixel
@236,405 Say aBotoes[k+047] OF oDlgb Size 90,15 Pixel
@236,505 Say aBotoes[k+048] OF oDlgb Size 90,15 Pixel
@266,005 Say aBotoes[k+049] OF oDlgb Size 90,15 Pixel
@266,105 Say aBotoes[k+050] OF oDlgb Size 90,15 Pixel
@266,205 Say aBotoes[k+051] OF oDlgb Size 90,15 Pixel
@266,305 Say aBotoes[k+052] OF oDlgb Size 90,15 Pixel
@266,405 Say aBotoes[k+053] OF oDlgb Size 90,15 Pixel
@266,505 Say aBotoes[k+054] OF oDlgb Size 90,15 Pixel


ACTIVATE MSDIALOG oDlgb CENTERED


Return  